version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: 
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
